### ISSUE TITLE
US 8 Favorite button

### ISSUE THREAD

**Issue by mulewile** [mulewile/capstone-project#10]
## Value proposition

As an user
I want to mark some events as important or favourite

so that I can find easily find them.

## Description

![favourite-button](https://user-images.githubusercontent.com/125578511/233674277-faf9ba3e-1de2-41d4-af15-d6302ba43e05.png)

## Acceptance criteria

- [ ] The favorite-button is displayed on the details page.
- [ ] Clicking the favourite-button on a non-favourite event saves it as a favourite.
- [ ] Clicking the favorite-button on a favourite piece removes it from favourites.

## Tasks

- [ ] Create a FavouriteButton
- [ ] Create toggle function and store values of user activity with button in state.
- [ ] Pass FavoriteButton props: isFavorite, onToggleFavorite
- [ ] Render the favourite button on event details page.

Size: M
