### ISSUE TITLE
Expenses Field US 7.

### ISSUE THREAD

**Issue by mulewile** [mulewile/capstone-project#17]
## Value proposition

As a user I want to be able to track my expenses
in order to have a good financial overview of event costs.

## Description

![US 8](https://user-images.githubusercontent.com/125578511/235939973-1a0d2e31-b14e-4c87-84d1-81261a871b77.png)

## Acceptance criteria

- [ ] Expenses field set is displayed in the event form.
- [ ] Gaining access to the input fields by whatever method, mouse, keyboard, siri, alexa etc... allows the user to enter preferred data, i.e only numbers allowed.

## Tasks

- [ ] Create expenses field set in the existing form.
- [ ] Update the schema
- [ ] Update the list component
- [ ] Update the details component.

Size: L

**Comment by CJAkkuec** [comment]
I'm going to be just the tiniest little bit nit-picky here. 🤭 

> As a user
> I want to see and interact with an expenses field set,
> in order to have a good financial plan of events.

I understand that the "see" here may be my fault, but this part can be omitted, as not everyone is capable of sight, but they'll still be able to interact with the form. (Or should be.)

I'd suggest something according to these lines:
"As a user I want to be able to track my expenses in order to better balance my finances."

> Expenses field set is displayed in the event form.
> Clicking on an input field allows the user to enter preferred data.

Strictly speaking it's not just clicking. Using the tab key should also get you there. 😄 So the user should be able to enter their data successfully, regardless of their method. You might also specify what the user _shouldn't_ be able to do, such as input text for what should be a number, etc.

**Comment by mulewile** [comment]
I see the nit-picky eyes 😀, I actually thought accessibility issues are tackled in a different user Stor.
> As a user
I want to see and interact with an expenses field set,
in order to have a good financial plan of events.

**Comment by mbosselmann** [comment]
LGTM! 🦊
