### ISSUE TITLE
Favourite Button US 8

### ISSUE THREAD

**Issue by mulewile** [mulewile/capstone-project#18]
## Value proposition

As a user
I want to be able to mark events as favourites or important
in order to know which events might need priority planning etc.

## Description

![US 8](https://user-images.githubusercontent.com/125578511/235960738-b43230f6-0705-4f3c-9532-f55b1051cfec.png)

## Acceptance criteria

- [ ] A button with an appropriate like emoji is displayed in the event form.
- [ ] Gaining access to the favourite button by whatever method, mouse, keyboard, siri, alexa etc... allows the user to toggle emoji.

## Tasks

- [ ] Create like button
- [ ] Create state.
- [ ] Update event details card.

Size:  L

**Comment by mulewile** [comment]
Hi Mareike
Thanks! 🚀
