### ISSUE TITLE
Event Countdown Timer US 9

### ISSUE THREAD

**Issue by mulewile** [mulewile/capstone-project#19]
## Value proposition

As a user,
I want to be reminded of event deadlines,
in order to be able to plan accordingly and not miss deadlines....etc.

## Description

![Screenshot 2023-05-04 at 09 25 30](https://user-images.githubusercontent.com/125578511/236150441-a492a0a5-e58f-4de1-83e7-4501c365be19.png)

## Acceptance criteria

- [ ] A countdown timer is displayed on each event item on the list page.
- [ ] As the event approaches the remaining time is updated.

## Tasks

- [ ] Create Countdown timer component. 
- [ ] Create a state for initial date and remaining time. 
- [ ] Create a useEffect hook.
- [ ] Update the list component

Size: XL

**Comment by mbosselmann** [comment]
Hi Bill,
great job! 💪 
This user story looks also good to me! 🦊
