### ISSUE TITLE
Favourite button displayedo event list.

### ISSUE THREAD

**Issue by mulewile** [mulewile/capstone-project#21]
## Value proposition

As a user
I want to have an overview of which events I am more interested in
in order to prioritise my planning.

## Description

![US 10](https://user-images.githubusercontent.com/125578511/236445175-c954f551-cc30-46fe-a2e9-e13a8ea9334f.png)

## Acceptance criteria

- [ ] A like emoji is displayed on EventList items depending on the boolean value set in specific cards.

## Tasks

- [ ] Create a span element for the hear or fitting emoji in the EventList component.
- [ ] Pass the state of the button to the EventList component to conditionally render the like button

Size: M

**Comment by mulewile** [comment]
@ahohnsen Thanks Andrea.

> I am wondering if there is any specific functionality associated with the heart icon. Can users click on the heart to mark an event as a favorite? If that is the case, you should update your wireframes. Currently, non-favorite events do not show any icon to mark them as favorite. If this user story does not include the favorite functionality, I would argue that the feature is incomplete.

Each event details card has a button/clickable emoji(I covered this in an earlier US). This current user story is just to display the heart emoji on specific events that  are liked. If the event card was not marked "liked" then nothing appears, if it was marked "liked" then the heart appears. I decided not to have this functionality directly on event items on the list in order to crowd the items.

**Comment by ahohnsen** [comment]
Ah, okay. Thanks for the explanation 🙂 
If you have not implemented the previous US, where you covered the functionality, then I would suggest to merge these two US to one.

**Comment by mulewile** [comment]
Combined and actually changed the method of the earlier user story.
