### ISSUE TITLE
Reminders/Notifications US11

### ISSUE THREAD

**Issue by mulewile** [mulewile/capstone-project#22]
## Value proposition

As a user
I want to be reminded of events that are approaching even when I am not using the app,
in order not to miss events.

## Description
![US 11](https://user-images.githubusercontent.com/125578511/236490489-fa527778-70fe-4a48-bb80-31f316c61117.png)

## Acceptance criteria

- [ ] Upcoming event notification pops up when user is not using app.
- [ ] Notifications appear a week before the event starts.
- [ ] Clicking on the x button on top right corner of the notification clears the notification from the screen.

## Tasks

- [ ] Research on creating push notifications.
- [ ] Create x /close/clear button for the notification.
- [ ] Link already created date timer to notification modal.
- [ ] Render notification conditionally.

Size: L

**Comment by mulewile** [comment]
Thanks once again for the tips. :)
