### ISSUE TITLE
[user story title]

### ISSUE THREAD

**Issue by mulewile** [mulewile/capstone-project#3]
## Value proposition

As a [user]
I want to [see a list of events]
in order to [need]

## Description

[image of wireframe]

## Acceptance criteria

- [ ] All events are displayed as a list
- [ ] Name of the person is displayed
- [ ] Event date is displayed
- [ ] favourite button is displayed

## Tasks

- [ ] Fetch data
- [ ] Create events components

**Comment by F-Kirchhoff** [comment]
Hey BIll,
this is almost ready to go! The size is perfect, the starting point of your app is great, and the acceptance criteria are good too. Here is the stuff you need to change:
- remove the add button from the wire frame - no buttons without implemented functionality in your app
- what is the yellow element? Please describe it in your acceptance criteria and tasks
- add some more tasks for the creation, mapping and display of your event list
- first we are not fetching the event but using dummy data in a simple array in your app. So you can replace the fetching task with "create dummy data array"

**Comment by mulewile** [comment]
>     * what is the yellow element? Please describe it in your acceptance criteria and tasks

Hey Felix, thanks for the feedback. The yellow button is supposed to indicate that the event is very important or that some essentials details are missing. I have not yet decided which one it will. My guess is that I do not to have it in the first user story just like the add button.
