### ISSUE TITLE
Event Details Page

### ISSUE THREAD

**Issue by mulewile** [mulewile/capstone-project#4]
## Value proposition

As a user
I want to be able to see the details of the event,
so that I can remind myself of the event details.

## Description

![details-page](https://user-images.githubusercontent.com/125578511/233120078-38bf2530-491e-4630-aa45-f8894a742f24.png)

## Acceptance criteria

- [ ] The name of the person celebrating the event is displayed.
- [ ] The event name is displayed.
- [ ] The event location is displayed.
- [ ] Messages, notes, gift ideas of the user are displayed.
- [ ] Tasks the user may have at the event are displayed.
- [ ] Number of guests attending the event is displayed.

## Tasks

- [ ] Create the component EventDetails
- [ ] Map over dummy data.
- [ ]  Display full details of the event.

Size: M

**Comment by ella-blaupause** [comment]
LGTM👍

**Comment by MateLoncar** [comment]
looks good to me now
