### ISSUE TITLE
Event Form

### ISSUE THREAD

**Issue by mulewile** [mulewile/capstone-project#5]
## Value proposition

As a user
I want to be able to see an add button, a form with input fields, a done button and a cancel button,
in order to create a new event card and be able to return to the events overview and confirm that it worked.

## Description

![Screenshot 2023-04-26 at 22 04 09](https://user-images.githubusercontent.com/125578511/234691037-95ae5a8e-dfe1-4086-81b1-d4defcd89816.png)

## Acceptance criteria
- [x] Clicking on the add button leads the user to the form.
- [x] Clicking on an input field allows the user to enter preferred data.
- [x] Clicking the done button saves the entered data,
 creates a event card and returns the user to the EventList page. 
- [x] Clicking on the cancel button button returns the user to the EventList page.

## Tasks
- [x] Create an EventForm component.
- [x] Create input fields.
- [x] Create a an add button.
- [x] Create a cancel button.
- [x] Create a done button.
- [x] useState to handle creation of new data (don't mutate!)
- [x] Map over form data to create a new card.
- [x] Find() specific event.
- [x] Create a router.

Size: XL

**Comment by CJAkkuec** [comment]
> As a user
> I want to see a form
> in order to input event details.

I'd probably suggest that the user doesn't want to just see a form, but enter data into it. Such as, a user wants to enter event details into a form so they can create a new event.

I think this User Story should be about the creation of a new event + routing back to the event overview.

Here's why:

Acceptable behavior of a form is to receive data and to process it. If I hit "done" and I'm just being routed to the overview but the data is nowhere to be found, that is not "acceptable".

So you need to:

1. Create a form
2. Process the user input (maybe it creates a new event card, etc ...)
3. Route back to the overview, so the user can see that it worked (e.g. there's a new event card now, etc ...)

The size of this User Story is likely more large rather than small.

**Comment by mulewile** [comment]
Thanks,  I should have explicitly included some points rather than imply them.
