### ISSUE TITLE
Delete and Edit Buttons on Event Details Page

### ISSUE THREAD

**Issue by mulewile** [mulewile/capstone-project#6]
## Value proposition

As a user
I want to edit event details or remove an event card,
in order to add information or remove outdated events etc.

## Description

![delete:edit](https://user-images.githubusercontent.com/125578511/233376053-fcbaeeef-823f-47b4-8008-bf1b7f2d5a51.png)

## Acceptance criteria

- [ ] The delete-button displayed on the details page.
- [ ] The edit-button is displayed on the details page.
- [ ] Clicking the delete-button on a removes the event card, updates the event list accordingly..
- [ ] Clicking the edit-button allows the user to add or remove data to the event card. and updates the event list      accordingly.

## Tasks

- [ ] Create a button component.
- [ ] Add a delete button to the event card.
- [ ] Add an edit button to the event card.
- [ ] Render the delete button in the event card component.
- [ ] Render the edit button in the event card component.
- [ ] Find the event card to remove.
- [ ] Map over new information to update the event card and the event list.
- [ ] Route accordingly.

Size: L
