### ISSUE TITLE
Delete button on event card

### ISSUE THREAD

**Issue by mulewile** [mulewile/capstone-project#8]
## Value proposition

As a user
I want to see and interact with a delete button
in order to remove outdated or canceled events.

## Description

![delete-button](https://user-images.githubusercontent.com/125578511/233607248-90fa5282-1602-4111-bec8-6fc77b6a4184.png)

## Acceptance criteria

- [ ] The delete-button displayed on the details page.
- [ ] Clicking the delete-button removes the event card, updates the event list accordingly..

## Tasks

- [ ] Create a button component.
- [ ] Add a delete button to the event card.
- [ ] Render the delete button in the event card component.
- [ ] FindbyID the event card to remove.
- [ ] Update the event card and the event list.
- [ ] Create route for the delete button.

Size: S
