### ISSUE TITLE
US 7 - Data persistance

### ISSUE THREAD

**Issue by mulewile** [mulewile/capstone-project#9]
## Value proposition

As a user,
I want to persist any changes I make in the app,
so that the data will not be lost when I refresh the page or when I close the app.

## Description

Backend

## Acceptance criteria

- [ ] All user operations i.e. Create, Read, Update and Delete should be persisted when app is closed or page is refreshed.

## Tasks

- [ ] Install the package use-local-storage-state.
- [ ] Use the useLocalStorageState hook to store the CRUD operations in state.

Size: L

**Comment by CJAkkuec** [comment]
Very good!
